# Generated by Django 5.2 on 2025-04-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_image_alter_recipe_image_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
