# Generated by Django 5.2 on 2025-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_review_avg_rating_remove_review_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
