# Generated by Django 5.2 on 2025-05-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_review_avg_rating_review_total_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='total_reviews',
        ),
    ]
