# Generated by Django 5.2 on 2025-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_review_avg_rating_remove_review_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='avg_rating',
            field=models.FloatField(default=0.0, help_text='Calculated average of all reviews', verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Number of reviews received', verbose_name='Total Reviews'),
        ),
    ]
