# Generated by Django 5.2 on 2025-05-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_instruction_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Comments'),
        ),
    ]
